server:
  port: 8096
  ssl:
    enabled: false

  tomcat:
    connection-timeout: 10000
#?????



logging:
  level:
    reactor:
      netty: TRACE
    org:
      springframework:
        cloud:
          gateway: TRACE
spring:
  datasource:
    dynamic:
      primary: master #设置默认的数据源或者数据源组,默认值即为master
      strict: false #严格匹配数据源,默认false. true未匹配到指定数据源时抛异常,false使用默认数据源
      datasource:
        master:
          url: jdbc:mysql://192.168.0.110:3306/db_order_0
          username: root
          password: 123456
          driver-class-name: com.mysql.jdbc.Driver # 3.2.0开始支持SPI可省略此配置
  cloud:
    gateway:
      httpclient:
        ssl:
          useInsecureTrustManager: true
        pool:
          max-idle-time: 10000
      routes:
        #????
        - id: google22
          uri: https://www.cnblogs.com
          predicates:
            - Path=/drive
        - id: google
          uri: https://google.com
          predicates:
            - Path=/google/{param}
          filters:
            - RewritePath=/google(?<segment>/?.*),/search
            - AddRequestParameter=q,{param}
        - id: path_route
          uri: https://webhook.site
          predicates:
            - Method=GET,POST
            - Path=/echo/**
          filters:
            - StripPrefix=1
            - Custom=a,b,c,d,e
# http://10.170.200.218:8096/echo/a238e6c5-c3e5-4060-a667-61eef751b473

        - id: path_route2
          uri: http://10.170.129.13:83
          predicates:
            - Method=GET,POST
            - Path=/soap/**
          filters:
            - StripPrefix=1
            - Custom=a,b,c,d,e

#      default-filters:
#        - Default=a1,b1,c1,d1,e1
